server {
    listen 80;
    server_name localhost;

    # Frontend
    location / {
        proxy_pass http://frontend:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Backend API
    location /auth/ {
        proxy_pass http://backend:5000/auth/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /empleados {
        proxy_pass http://backend:5000/empleados;
        proxy_set_header Host $host;
    }

    location /cargos {
        proxy_pass http://backend:5000/cargos;
        proxy_set_header Host $host;
    }

    location /departamentos {
        proxy_pass http://backend:5000/departamentos;
        proxy_set_header Host $host;
    }
}
